[workspace]
members = [
    "sftp-scanner",
    "core",
    "dispatcher"
]

[workspace.package]
version = "1.4.0"
authors = ["1Optic B.V. <info@1optic.io>"]
edition = "2021"
license = "GPL-3.0-or-later"
