[package]
name = "cortex-core"
version = "0.1.21"
authors = ["Alfred Blokland <alfred.blokland@hendrikx-itc.nl>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
chrono = { version = "0.4", features = ["serde"] }
ssh2 = "0.9"
owning_ref = "0.4"
log = "0.4"
error-chain = "0.12"
